spring:
  # 静态资源处理
  resource:
    add-mapping: true
    cache:
      cachecontrol:
        max-age: 3600
      chain:
        # 资源链
        cache: true
        # 启用资源链，默认禁用
        enabled: true
        # 压缩资源 gzip
        compressed: true
        html-application-cache: true
    static-locations: classpath:/static/
  # thymeleaf ??
  thymeleaf:
    # ????
    cache: false
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xxxx
    password: 1234
    hikari:
      # ?????
      pool-name: DateHikariCP
      # ??????
      minimum-idle: 5
      # ?????????????10??
      idle-timeout: 180000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0??????
      max-lifetime: 180000
      # ??????
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5


# Mybatis-plus ??
mybatis-plus:
  # ?? Mapper.xml ????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ?? Mybatis ?????????????????
  type-aliases-package: com.kelin.seckill.pojo

# Mybatis SQL ?????????????? Mapper.xml ?????
logging:
  level:
    com.kelin.seckill.mapper: debug
